os:
  - linux
  - osx

env:
  global:
    MINICONDA: $HOME/miniconda
    BASH_ENV: $HOME/.bashrc

cache:
  directories:
    - conda_cache

install:
  - ./ci_conda_prep.sh
  - export PATH=$MINICONDA/bin:$PATH
  - hash -r
  - source activate test_env
  - mkdir reports
script:
  - python setup.py install
  - pytest --junit-xml reports/report.xml -n 2

  
