channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake
  # rpy2 pinned to keep conda from spinning for ever trying to resolve dependencies
  - rpy2 =2.8.5
  - click
  - pyyaml
  - python-drmaa
  - pandas  #=0.20.*
  - xlrd # for excel support
  # for tests:
  - networkx
  - pytest
  - pygraphviz
  - yappi

